<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-17T10:32:16 EST" name="FunctionalTestSuite" finished-at="2025-02-17T10:32:42 EST" duration-ms="26425">
    <groups>
      <group name="datadriven">
        <method signature="TC003_Lodinddt.ddtlogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC003_Lodinddt@6175619b]" name="ddtlogin" class="testCases.TC003_Lodinddt"/>
      </group> <!-- datadriven -->
      <group name="regression">
        <method signature="TC001_LoginTest.verifylogin(java.util.HashMap)[pri:0, instance:testCases.TC001_LoginTest@165b8a71]" name="verifylogin" class="testCases.TC001_LoginTest"/>
        <method signature="TC002AddProductCatalog.addproduct()[pri:0, instance:testCases.TC002AddProductCatalog@55795845]" name="addproduct" class="testCases.TC002AddProductCatalog"/>
      </group> <!-- regression -->
      <group name="sanity">
        <method signature="TC001_LoginTest.verifylogin(java.util.HashMap)[pri:0, instance:testCases.TC001_LoginTest@165b8a71]" name="verifylogin" class="testCases.TC001_LoginTest"/>
      </group> <!-- sanity -->
    </groups>
    <test started-at="2025-02-17T10:32:16 EST" name="Test" finished-at="2025-02-17T10:32:42 EST" duration-ms="26425">
      <class name="testCases.TC001_LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testCases.TC001_LoginTest@165b8a71]" started-at="2025-02-17T10:32:27 EST" name="setup" finished-at="2025-02-17T10:32:34 EST" duration-ms="6381" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifylogin(java.util.HashMap)[pri:0, instance:testCases.TC001_LoginTest@165b8a71]" started-at="2025-02-17T10:32:34 EST" name="verifylogin" data-provider="jsondata" finished-at="2025-02-17T10:32:34 EST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
The local variable data may not have been initialized
The local variable data may not have been initialized
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.Error: Unresolved compilation problems: 
The local variable data may not have been initialized
The local variable data may not have been initialized

at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.Error: Unresolved compilation problems: 
The local variable data may not have been initialized
The local variable data may not have been initialized

at testCases.TC001_LoginTest.jsondata(TC001_LoginTest.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifylogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCases.TC001_LoginTest@165b8a71]" started-at="2025-02-17T10:32:34 EST" name="teardown" finished-at="2025-02-17T10:32:34 EST" duration-ms="160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC001_LoginTest -->
      <class name="testCases.TC002AddProductCatalog">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testCases.TC002AddProductCatalog@55795845]" started-at="2025-02-17T10:32:16 EST" name="setup" finished-at="2025-02-17T10:32:23 EST" duration-ms="6733" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="addproduct()[pri:0, instance:testCases.TC002AddProductCatalog@55795845]" started-at="2025-02-17T10:32:23 EST" name="addproduct" finished-at="2025-02-17T10:32:27 EST" duration-ms="4186" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addproduct -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCases.TC002AddProductCatalog@55795845]" started-at="2025-02-17T10:32:27 EST" name="teardown" finished-at="2025-02-17T10:32:27 EST" duration-ms="200" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC002AddProductCatalog -->
      <class name="testCases.TC003_Lodinddt">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:testCases.TC003_Lodinddt@6175619b]" started-at="2025-02-17T10:32:34 EST" name="setup" finished-at="2025-02-17T10:32:42 EST" duration-ms="7528" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="ddtlogin(java.lang.String,java.lang.String)[pri:0, instance:testCases.TC003_Lodinddt@6175619b]" started-at="2025-02-17T10:32:42 EST" name="ddtlogin" data-provider="LoginData" finished-at="2025-02-17T10:32:42 EST" duration-ms="0" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.io.FileNotFoundException: .\testData\Opencart_LoginData.xlsx (The system cannot find the file specified)]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: .\testData\Opencart_LoginData.xlsx (The system cannot find the file specified)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)
at org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)
at org.testng.internal.Parameters.handleParameters(Parameters.java:809)
at org.testng.internal.Parameters.handleParameters(Parameters.java:734)
at org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
at org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.io.FileNotFoundException: .\testData\Opencart_LoginData.xlsx (The system cannot find the file specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
at utilities.ExcelUtility.getRowCount(ExcelUtility.java:39)
at utilities.DataProviders.getData(DataProviders.java:16)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ddtlogin -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:testCases.TC003_Lodinddt@6175619b]" started-at="2025-02-17T10:32:42 EST" name="teardown" finished-at="2025-02-17T10:32:42 EST" duration-ms="208" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testCases.TC003_Lodinddt -->
    </test> <!-- Test -->
  </suite> <!-- FunctionalTestSuite -->
</testng-results>
